// SnapNext AI email templates. Each export returns { subject, html, text }.
// All templates are mobile-friendly (single-column, max-width 600px, inline CSS).

const SUPPORT_EMAIL = process.env.SUPPORT_EMAIL || 'support@snapnext.ai';

function shell({ title, preheader, bodyHtml, footerExtra = '' }) {
  const baseUrl = (process.env.NEXT_PUBLIC_BASE_URL || process.env.NEXT_PUBLIC_APP_URL || '').replace(/\/$/, '');
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)}</title></head>
<body style="margin:0;padding:0;background:#0b0414;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif;">
  <span style="display:none!important;opacity:0;visibility:hidden;max-height:0;max-width:0;overflow:hidden;mso-hide:all;">${escape(preheader || '')}</span>
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#0b0414;padding:32px 16px;"><tr><td align="center">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:560px;background:#ffffff;border-radius:20px;overflow:hidden;">
      <tr><td style="padding:28px 28px 0;text-align:center;"><table role="presentation" cellpadding="0" cellspacing="0" style="margin:0 auto;"><tr><td><img src="${escape(baseUrl)}/logo.png" width="48" height="48" alt="SnapNext AI" style="display:block;object-fit:contain;border:0;"/></td><td style="padding-left:10px;font-size:18px;font-weight:700;color:#0b0414;">SnapNext AI</td></tr></table></td></tr>
      <tr><td style="padding:24px 28px 8px;color:#0b0414;">${bodyHtml}</td></tr>
      <tr><td style="padding:24px 28px 28px;border-top:1px solid #f0eef4;color:#6b7280;font-size:12px;line-height:1.6;">Need help? Contact <a href="mailto:${SUPPORT_EMAIL}" style="color:#7c3aed;text-decoration:none;">${SUPPORT_EMAIL}</a><br/>© SnapNext AI — Your memories, beautifully organized.${footerExtra}</td></tr>
    </table>
  </td></tr></table>
</body></html>`;
}

function button(label, url) { return `<table role="presentation" cellpadding="0" cellspacing="0" style="margin:24px auto 8px;"><tr><td style="background:linear-gradient(135deg,#ec4899,#7c3aed);border-radius:999px;"><a href="${escape(url)}" style="display:inline-block;padding:14px 28px;color:#fff;text-decoration:none;font-weight:600;font-size:15px;">${escape(label)}</a></td></tr></table>`; }
function escape(s) { return String(s == null ? '' : s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;'); }
function unsubscribeFooter(unsubUrl) { return unsubUrl ? `<br/><br/><a href="${escape(unsubUrl)}" style="color:#9ca3af;text-decoration:underline;">Unsubscribe from these emails</a>` : ''; }

export function verifyEmailTemplate({ name, verifyUrl }) { const bodyHtml = `<h1 style="margin:0 0 8px;font-size:24px;">Welcome to SnapNext AI ✨</h1><p style="margin:0;color:#374151;font-size:15px;line-height:1.55;">Hi ${escape(name || 'there')}, verify your email to secure your account.</p>${button('Verify email', verifyUrl)}`; return { subject:'Verify your SnapNext AI email', html:shell({title:'Verify your email',preheader:'Confirm your email.',bodyHtml}), text:`Verify your email: ${verifyUrl}` }; }
export function welcomeTemplate({ name, appUrl }) { const bodyHtml = `<h1 style="margin:0 0 8px;font-size:24px;">You're in, ${escape(name || 'friend')} 🎉</h1><p style="color:#374151;font-size:15px;">Your account is ready.</p>${button('Open SnapNext AI', appUrl || '#')}`; return { subject:'Welcome to SnapNext AI', html:shell({title:'Welcome',preheader:'Your account is ready.',bodyHtml}), text:`Open SnapNext AI: ${appUrl || ''}` }; }
export function forgotPasswordTemplate({ name, resetUrl }) { const bodyHtml = `<h1 style="margin:0 0 8px;font-size:24px;">Reset your password</h1><p style="color:#374151;font-size:15px;">Hi ${escape(name || 'there')}, use this secure link to reset your password.</p>${button('Reset password', resetUrl)}`; return { subject:'Reset your SnapNext AI password', html:shell({title:'Reset password',preheader:'Your secure reset link.',bodyHtml}), text:`Reset your password: ${resetUrl}` }; }
export function passwordChangedTemplate({ name, supportEmail = SUPPORT_EMAIL }) { const bodyHtml = `<h1 style="margin:0 0 8px;font-size:24px;">Your password was changed ✅</h1><p style="color:#374151;font-size:15px;">Hi ${escape(name || 'there')}, your password was changed. Contact ${escape(supportEmail)} if this was not you.</p>`; return { subject:'Your SnapNext AI password was changed', html:shell({title:'Password changed',preheader:'Security notice.',bodyHtml}), text:`Your password was changed. Contact ${supportEmail} if this was not you.` }; }

export function familyInviteTemplate({ ownerName, householdName, role, joinUrl, expiresAt }) { const bodyHtml = `<h1 style="margin:0 0 8px;font-size:24px;">Join ${escape(householdName || 'a SnapNext Family')} 👨‍👩‍👧‍👦</h1><p style="color:#374151;font-size:15px;line-height:1.55;">${escape(ownerName || 'A family member')} invited you as an ${escape(role || 'adult')} member. Your personal library stays private unless you intentionally share something.</p>${button('Accept Family invitation', joinUrl)}<p style="color:#6b7280;font-size:12px;">This secure invitation expires ${escape(expiresAt || 'in 7 days')} and only works for the invited email address.</p>`; return { subject:`${ownerName || 'Someone'} invited you to ${householdName || 'SnapNext Family'}`, html:shell({title:'Family invitation',preheader:'A private Family invitation is waiting.',bodyHtml}), text:`Join ${householdName || 'SnapNext Family'}: ${joinUrl}` }; }
export function familyJoinedTemplate({ memberName, memberEmail, familyUrl }) { const bodyHtml = `<h1 style="margin:0 0 8px;font-size:24px;">A new member joined 🎉</h1><p style="color:#374151;font-size:15px;">${escape(memberName || memberEmail || 'Your family member')} accepted the invitation. Their personal library remains private by default.</p>${button('Open Family workspace', familyUrl)}`; return { subject:`${memberName || memberEmail || 'A family member'} joined your SnapNext Family`, html:shell({title:'Family member joined',preheader:'Your household has a new member.',bodyHtml}), text:`${memberName || memberEmail || 'A family member'} joined. Open: ${familyUrl}` }; }
export function familyMembershipEndedTemplate({ memberName, action, familyUrl }) { const verb = action === 'removed' ? 'was removed from' : 'left'; const bodyHtml = `<h1 style="margin:0 0 8px;font-size:24px;">Family membership updated</h1><p style="color:#374151;font-size:15px;">${escape(memberName || 'A member')} ${verb} your SnapNext Family. Their personal files were not deleted.</p>${button('Open Family workspace', familyUrl)}`; return { subject:'Your SnapNext Family membership changed', html:shell({title:'Family update',preheader:'A household membership changed.',bodyHtml}), text:`${memberName || 'A member'} ${verb} your Family.` }; }

export function billingUpgradeTemplate({ name, planName, unsubscribeUrl }) { const bodyHtml=`<h1>Welcome to ${escape(planName)} 🚀</h1><p>Thanks for upgrading, ${escape(name || 'friend')}.</p>`; return {subject:`Welcome to ${planName}`,html:shell({title:'Plan upgrade',preheader:'Your upgrade is active.',bodyHtml,footerExtra:unsubscribeFooter(unsubscribeUrl)}),text:`You're now on ${planName}.`}; }
export function billingDowngradeTemplate({ name, planName, unsubscribeUrl }) { const bodyHtml=`<h1>Plan changed to ${escape(planName)}</h1><p>Hi ${escape(name || 'friend')}, your plan was updated.</p>`; return {subject:'Your SnapNext AI plan was changed',html:shell({title:'Plan change',preheader:'Plan change confirmation.',bodyHtml,footerExtra:unsubscribeFooter(unsubscribeUrl)}),text:`Your plan was changed to ${planName}.`}; }
export function billingFailedTemplate({ name, retryUrl, unsubscribeUrl }) { const bodyHtml=`<h1>Payment failed</h1><p>Hi ${escape(name || 'friend')}, please update your payment method.</p>${retryUrl?button('Update payment',retryUrl):''}`; return {subject:'Payment failed — action required',html:shell({title:'Payment failed',preheader:'Please update billing.',bodyHtml,footerExtra:unsubscribeFooter(unsubscribeUrl)}),text:'Your payment failed.'}; }
export function downloadReadyTemplate({ name, downloadUrl, unsubscribeUrl }) { const bodyHtml=`<h1>Your export is ready 📦</h1><p>Hi ${escape(name || 'friend')}, your archive is ready.</p>${button('Download archive',downloadUrl)}`; return {subject:'Your SnapNext AI export is ready',html:shell({title:'Export ready',preheader:'Your archive is ready.',bodyHtml,footerExtra:unsubscribeFooter(unsubscribeUrl)}),text:`Your export is ready: ${downloadUrl}`}; }
export function favoritesInviteTemplate({ name, fromName, acceptUrl, unsubscribeUrl }) { const bodyHtml=`<h1>${escape(fromName || 'Someone')} added you as a favorite 💖</h1>${button('Accept invite',acceptUrl)}`; return {subject:`${fromName || 'A friend'} added you as a favorite`,html:shell({title:'Favorite invitation',preheader:'A request is waiting.',bodyHtml,footerExtra:unsubscribeFooter(unsubscribeUrl)}),text:`Accept invite: ${acceptUrl}`}; }
export function communityInviteTemplate({ communityName, acceptUrl, unsubscribeUrl }) { const bodyHtml=`<h1>You're invited to “${escape(communityName)}”</h1>${button('Open invitation',acceptUrl)}`; return {subject:`You're invited to ${communityName}`,html:shell({title:'Community invite',preheader:'An invite is waiting.',bodyHtml,footerExtra:unsubscribeFooter(unsubscribeUrl)}),text:`Join community: ${acceptUrl}`}; }

export const TEMPLATE_REGISTRY = {
  verify_email:{fn:verifyEmailTemplate,transactional:true,prefKey:null}, welcome:{fn:welcomeTemplate,transactional:true,prefKey:null}, forgot_password:{fn:forgotPasswordTemplate,transactional:true,prefKey:null}, password_changed:{fn:passwordChangedTemplate,transactional:true,prefKey:null},
  family_invite:{fn:familyInviteTemplate,transactional:true,prefKey:null}, family_joined:{fn:familyJoinedTemplate,transactional:true,prefKey:null}, family_membership_ended:{fn:familyMembershipEndedTemplate,transactional:true,prefKey:null},
  billing_upgrade:{fn:billingUpgradeTemplate,transactional:true,prefKey:null}, billing_downgrade:{fn:billingDowngradeTemplate,transactional:true,prefKey:null}, billing_failed:{fn:billingFailedTemplate,transactional:true,prefKey:null}, download_ready:{fn:downloadReadyTemplate,transactional:true,prefKey:null}, favorites_invite:{fn:favoritesInviteTemplate,transactional:false,prefKey:'favorites'}, community_invite:{fn:communityInviteTemplate,transactional:false,prefKey:'community'}
};