'use client';
import { useEffect, useMemo, useState } from 'react';
import { apiFetch, mediaSrc } from '@/lib/api-client';
import { toast } from 'sonner';
import { Search, Heart, Trash2, Download, Star, CheckCircle2, Image as ImageIcon, Film, Pencil, FileText, Camera } from 'lucide-react';
import Link from 'next/link';

const NAME_KEY = 'snapnext.personNames.v1';
function cleanName(v){ const s=String(v||'').trim(); return !s || /^person\s*\d+$/i.test(s) || ['person','people','unknown','face','user'].includes(s.toLowerCase()) ? 'Add name' : s; }

export default function GalleryPage(){
  const [items,setItems]=useState([]), [filter,setFilter]=useState('all'), [q,setQ]=useState(''), [search,setSearch]=useState('');
  const [selected,setSelected]=useState(new Set()), [names,setNames]=useState({}), [viewer,setViewer]=useState(null);
  useEffect(()=>{ try{setNames(JSON.parse(localStorage.getItem(NAME_KEY)||'{}'))}catch{} },[]);
  async function load(){ const p=new URLSearchParams({filter}); if(search)p.set('q',search); try{const d=await apiFetch('/media?'+p); setItems(d.items||[])}catch(e){toast.error(e.message)} }
  useEffect(()=>{load()},[filter,search]);
  const label=n=>names[n]||cleanName(n);
  const saveName=(raw)=>{ const v=window.prompt('Name this face',label(raw)==='Add name'?'':label(raw)); if(!v)return; const next={...names,[raw]:v.trim()}; setNames(next); try{localStorage.setItem(NAME_KEY,JSON.stringify(next))}catch{} };
  const people=useMemo(()=>{const m=new Map(); for(const item of items){ for(const f of (item.aiAnalysis?.faces||[])){ const k=String(f||'').trim(); if(!k)continue; const p=m.get(k)||{name:k,count:0,sample:null,fav:false}; p.count++; p.fav=p.fav||!!item.favorite; if(!p.sample&&item.kind==='photo')p.sample=item.id; m.set(k,p); }} return [...m.values()].sort((a,b)=>Number(b.fav)-Number(a.fav)||b.count-a.count).slice(0,16)},[items]);
  const suggestions=useMemo(()=>{ const set=new Set(['family','celebration','recent photos','recent videos','screenshots','docs']); people.forEach(p=>set.add(label(p.name))); items.forEach(i=>{(i.aiAnalysis?.tags||[]).forEach(t=>set.add(String(t))); if(i.aiAnalysis?.autoAlbum)set.add(i.aiAnalysis.autoAlbum)}); const s=q.toLowerCase().trim(); return s?[...set].filter(x=>x.toLowerCase().includes(s)).slice(0,6):[] },[q,people,items,names]);
  const go=(v=q)=>setSearch(String(v||'').trim());
  const shortcut=t=>{ if(t==='photos'){setFilter('photo');setQ('');setSearch('')} if(t==='videos'){setFilter('video');setQ('');setSearch('')} if(t==='screenshots'){setFilter('all');setQ('screenshot');setSearch('screenshot')} if(t==='docs'){setFilter('all');setQ('doc');setSearch('doc')} };
  const fav=async id=>{await apiFetch(`/media/${id}/favorite`,{method:'POST'});load()};
  const trash=async id=>{await apiFetch(`/media/${id}/trash`,{method:'POST'});setViewer(null);load();toast('Moved to trash')};
  const dl=async item=>{const r=await fetch(mediaSrc(item.id)); const b=await r.blob(); const u=URL.createObjectURL(b); const a=document.createElement('a'); a.href=u; a.download=item.name; a.click(); URL.revokeObjectURL(u)};
  const toggle=id=>{const n=new Set(selected); n.has(id)?n.delete(id):n.add(id); setSelected(n)};
  const bulk=async action=>{if(!selected.size)return; await apiFetch('/media/bulk',{method:'POST',body:JSON.stringify({ids:[...selected],action})}); setSelected(new Set()); load(); toast.success('Done')};
  const filters=[['all','All',ImageIcon],['photo','Photos',ImageIcon],['video','Videos',Film],['favorite','Favorites',Heart]];
  return <div className="space-y-5">
    <div className="flex items-center justify-between gap-3 flex-wrap"><h1 className="text-3xl font-bold">Gallery</h1><div className="flex items-center gap-2 flex-1 max-w-md ml-auto"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-white/40"/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')go()}} placeholder="Search memories" className="w-full pl-9 pr-3 py-2 rounded-full bg-white/5 border border-white/10 text-sm outline-none"/>{suggestions.length>0&&<div className="absolute left-0 right-0 top-full mt-2 z-30 rounded-2xl border border-white/10 bg-[#13091d] p-2 shadow-xl">{suggestions.map(s=><button key={s} onClick={()=>{setQ(s);go(s)}} className="block w-full text-left px-3 py-2 rounded-xl text-sm hover:bg-white/5">{s}</button>)}</div>}</div><button onClick={()=>go()} className="px-4 py-2 rounded-full bg-gradient-to-r from-pink-500 to-purple-600 text-sm font-semibold">Search</button></div></div>
    <div className="flex gap-2 overflow-x-auto pb-1">{filters.map(([id,txt,Icon])=><button key={id} onClick={()=>setFilter(id)} className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full text-sm whitespace-nowrap ${filter===id?'bg-gradient-to-r from-pink-500 to-purple-600':'bg-white/5 border border-white/10 text-white/70'}`}><Icon className="h-3.5 w-3.5"/>{txt}</button>)}</div>
    {filter==='favorite'&&<section className="rounded-3xl border border-white/10 bg-white/[0.03] p-4 space-y-4"><div><h2 className="font-bold">Favorite faces</h2><p className="text-xs text-white/50">Tap a face to search. Tap the name to edit.</p></div>{people.length?<div className="flex gap-4 overflow-x-auto pb-1">{people.map(p=><div key={p.name} className="w-20 shrink-0 text-center"><button onClick={()=>{setQ(label(p.name));go(p.name)}} className="h-16 w-16 mx-auto rounded-full overflow-hidden border-2 border-pink-400/70 bg-white/5">{p.sample?<img src={mediaSrc(p.sample)} className="h-full w-full object-cover scale-[2.6] origin-top" style={{objectPosition:'50% 18%'}} alt=""/>:<span className="text-xs text-white/40">Face</span>}</button><button onClick={()=>saveName(p.name)} className="mt-1 inline-flex max-w-full items-center gap-1 text-[11px] font-semibold"><span className="truncate">{label(p.name)}</span><Pencil className="h-3 w-3 text-white/40"/></button></div>)}</div>:<p className="text-sm text-white/50">Favorite photos or upload analyzed memories to see face thumbnails.</p>}<div className="grid grid-cols-2 md:grid-cols-4 gap-2"><button onClick={()=>shortcut('photos')} className="rounded-2xl border border-white/10 bg-white/5 p-3 text-left text-sm"><Camera className="h-4 w-4 mb-2 text-pink-300"/>All recent photos</button><button onClick={()=>shortcut('videos')} className="rounded-2xl border border-white/10 bg-white/5 p-3 text-left text-sm"><Film className="h-4 w-4 mb-2 text-purple-300"/>All recent videos</button><button onClick={()=>shortcut('screenshots')} className="rounded-2xl border border-white/10 bg-white/5 p-3 text-left text-sm"><ImageIcon className="h-4 w-4 mb-2 text-sky-300"/>Screenshots</button><button onClick={()=>shortcut('docs')} className="rounded-2xl border border-white/10 bg-white/5 p-3 text-left text-sm"><FileText className="h-4 w-4 mb-2 text-emerald-300"/>Docs</button></div></section>}
    {selected.size>0&&<div className="sticky top-2 z-20 rounded-2xl border border-white/10 bg-[#0b0414]/90 px-3 py-2 flex items-center gap-2"><span className="text-sm">{selected.size} selected</span><div className="ml-auto flex gap-2"><button onClick={()=>bulk('favorite')} className="text-sm px-3 py-1.5 rounded-full bg-white/5 border border-white/10">Favorite</button><button onClick={()=>bulk('trash')} className="text-sm px-3 py-1.5 rounded-full bg-white/5 border border-white/10">Trash</button></div></div>}
    {items.length===0?<Empty/>:<div className="grid grid-cols-3 md:grid-cols-5 lg:grid-cols-6 gap-2">{items.map(m=><div key={m.id} className="group relative aspect-square rounded-xl overflow-hidden bg-white/5 cursor-pointer" onClick={()=>setViewer(m)}>{m.kind==='photo'?<img src={mediaSrc(m.id)} className="absolute inset-0 h-full w-full object-cover" alt=""/>:m.kind==='text'?<div className="absolute inset-0 p-3 text-xs text-white/70">{m.aiAnalysis?.caption||m.aiAnalysis?.description||m.name}</div>:<video src={mediaSrc(m.id)} className="absolute inset-0 h-full w-full object-cover" muted/>}<button onClick={e=>{e.stopPropagation();toggle(m.id)}} className={`absolute top-2 left-2 h-6 w-6 rounded-full grid place-items-center border ${selected.has(m.id)?'bg-pink-500 border-pink-500':'bg-black/40 border-white/30'}`}>{selected.has(m.id)&&<CheckCircle2 className="h-4 w-4"/>}</button>{m.favorite&&<Star className="absolute top-2 right-2 h-4 w-4 text-amber-300 fill-amber-300"/>}{m.kind==='video'&&<div className="absolute bottom-1 left-1 text-[10px] bg-black/60 px-1.5 rounded">VIDEO</div>}</div>)}</div>}
    {viewer&&<div className="fixed inset-0 z-50 bg-black/90 p-4 grid place-items-center" onClick={()=>setViewer(null)}><div className="max-w-5xl w-full grid md:grid-cols-[1fr_320px] gap-4" onClick={e=>e.stopPropagation()}><div className="rounded-2xl overflow-hidden bg-black grid place-items-center min-h-[300px]">{viewer.kind==='photo'?<img src={mediaSrc(viewer.id)} className="max-h-[80vh] w-full object-contain" alt=""/>:viewer.kind==='video'?<video src={mediaSrc(viewer.id)} className="max-h-[80vh] w-full" controls autoPlay/>:<div className="p-8">{viewer.aiAnalysis?.caption||viewer.aiAnalysis?.description}</div>}</div><div className="rounded-2xl bg-white/[0.04] border border-white/10 p-4"><div className="font-medium truncate">{viewer.name}</div><div className="text-xs text-white/50 mt-1">{new Date(viewer.createdAt).toLocaleString()}</div><div className="mt-4 grid grid-cols-3 gap-2"><button onClick={()=>fav(viewer.id)} className="text-xs py-2 rounded-xl bg-white/5 border border-white/10"><Heart className="h-4 w-4 mx-auto mb-1"/>Favorite</button><button onClick={()=>dl(viewer)} className="text-xs py-2 rounded-xl bg-white/5 border border-white/10"><Download className="h-4 w-4 mx-auto mb-1"/>Download</button><button onClick={()=>trash(viewer.id)} className="text-xs py-2 rounded-xl bg-white/5 border border-white/10"><Trash2 className="h-4 w-4 mx-auto mb-1"/>Trash</button></div></div></div></div>}
  </div>;
}
function Empty(){return <Link href="/upload" className="block rounded-2xl border border-dashed border-white/15 bg-white/[0.02] p-12 text-center"><div className="mx-auto h-12 w-12 rounded-2xl bg-gradient-to-br from-pink-500 to-purple-600 grid place-items-center"><ImageIcon className="h-5 w-5"/></div><div className="mt-3 font-medium">Your gallery is empty</div><div className="text-sm text-white/50">Upload some photos to get started.</div></Link>}
