'use client';
import { useEffect, useState } from 'react';
import { apiFetch } from '@/lib/api-client';
import { Loader2, Users, Mail, RefreshCw, X, UserMinus } from 'lucide-react';
import { toast } from 'sonner';

export default function FamilyPage(){
  const [data,setData]=useState(null); const [loading,setLoading]=useState(true); const [email,setEmail]=useState(''); const [role,setRole]=useState('adult'); const [busy,setBusy]=useState('');
  async function load(){try{setData(await apiFetch('/family'));}catch(e){toast.error(e.message);}finally{setLoading(false);}}
  useEffect(()=>{load();},[]);
  async function invite(e){e.preventDefault();setBusy('invite');try{const r=await apiFetch('/family',{method:'POST',body:JSON.stringify({action:'invite',email,role})});toast.success(r.invite.deliveryStatus==='sent'?'Invitation email sent.':'Invitation created, but email delivery needs attention.');setEmail('');await load();}catch(e){toast.error(e.message);}finally{setBusy('');}}
  async function resend(inviteId){setBusy(inviteId);try{const r=await apiFetch('/family',{method:'POST',body:JSON.stringify({action:'resend',inviteId})});toast.success(r.invite.deliveryStatus==='sent'?'Invitation resent with a new secure link.':'New invite created, but email delivery failed.');await load();}catch(e){toast.error(e.message);}finally{setBusy('');}}
  async function cancel(inviteId){setBusy(inviteId);try{await apiFetch(`/family?inviteId=${encodeURIComponent(inviteId)}`,{method:'DELETE'});toast.success('Invitation cancelled.');await load();}catch(e){toast.error(e.message);}finally{setBusy('');}}
  async function remove(memberId){setBusy(memberId);try{await apiFetch(`/family?memberId=${encodeURIComponent(memberId)}`,{method:'DELETE'});toast.success('Member removed. Their personal files remain safe.');await load();}catch(e){toast.error(e.message);}finally{setBusy('');}}
  async function leave(){setBusy('leave');try{await apiFetch('/family',{method:'POST',body:JSON.stringify({action:'leave'})});toast.success('You left the Family. Your personal library remains yours.');await load();}catch(e){toast.error(e.message);}finally{setBusy('');}}
  if(loading)return <Loader2 className="h-6 w-6 animate-spin"/>;
  if(!data?.family)return <div className="rounded-3xl border border-white/10 p-8 text-center"><Users className="mx-auto"/><h1 className="mt-3 text-3xl font-bold">Family plan</h1><p className="mt-2 text-white/60">Up to six separate accounts with shared plan capacity and private personal libraries.</p><a href="/billing" className="mt-5 inline-block rounded-full bg-white px-5 py-2 text-black">View plan</a></div>;
  const f=data.family; const owner=f.membership.role==='owner';
  return <div className="space-y-6">
    <section className="rounded-3xl border border-white/10 p-6"><h1 className="text-3xl font-bold">{f.household.name}</h1><p className="mt-2 text-white/60">{f.members.length} of {f.household.maxMembers} members. Storage and AI capacity are shared; personal libraries stay private unless intentionally shared.</p></section>
    {owner&&<section className="rounded-3xl border border-white/10 p-6"><h2 className="text-xl font-bold">Invite a family member</h2><p className="mt-1 text-sm text-white/50">SnapNext emails a secure seven-day invitation that only works for the invited address.</p><form onSubmit={invite} className="mt-4 grid gap-2 sm:grid-cols-[1fr_130px_auto]"><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="min-w-0 rounded-xl bg-white/5 px-4 py-3" placeholder="family@email.com"/><select value={role} onChange={e=>setRole(e.target.value)} className="rounded-xl bg-white/5 px-3 py-3"><option value="adult">Adult</option><option value="child">Child</option></select><button disabled={busy==='invite'} className="rounded-xl bg-white px-5 py-3 font-semibold text-black disabled:opacity-60">{busy==='invite'?'Sending…':'Send invite'}</button></form></section>}
    {owner&&f.invites?.length>0&&<section className="rounded-3xl border border-white/10 p-6"><h2 className="text-xl font-bold">Pending invitations</h2><div className="mt-3 space-y-2">{f.invites.map(i=><div key={i.id} className="flex flex-wrap items-center gap-3 rounded-xl bg-white/5 p-3"><Mail className="h-4 w-4 text-cyan-300"/><div className="min-w-0 flex-1"><div className="truncate">{i.email}</div><div className="text-xs text-white/45">{i.deliveryStatus==='sent'?'Email sent':'Delivery not confirmed'} · expires {new Date(i.expiresAt).toLocaleDateString()}</div></div><button disabled={busy===i.id} onClick={()=>resend(i.id)} className="inline-flex items-center gap-1 rounded-lg bg-white/10 px-3 py-2 text-xs"><RefreshCw className="h-3.5 w-3.5"/>Resend</button><button disabled={busy===i.id} onClick={()=>cancel(i.id)} className="inline-flex items-center gap-1 rounded-lg bg-red-500/10 px-3 py-2 text-xs text-red-200"><X className="h-3.5 w-3.5"/>Cancel</button></div>)}</div></section>}
    <section className="rounded-3xl border border-white/10 p-6"><h2 className="text-xl font-bold">Members</h2><div className="mt-3 space-y-2">{f.members.map(m=><div key={m.id} className="flex items-center gap-3 rounded-xl bg-white/5 p-3"><div className="min-w-0 flex-1"><div className="truncate">{m.email}</div><div className="text-xs capitalize text-white/50">{m.role}</div></div>{owner&&m.role!=='owner'&&<button disabled={busy===m.id} onClick={()=>remove(m.id)} className="inline-flex items-center gap-1 rounded-lg bg-red-500/10 px-3 py-2 text-xs text-red-200"><UserMinus className="h-3.5 w-3.5"/>Remove</button>}</div>)}</div>{!owner&&<button disabled={busy==='leave'} onClick={leave} className="mt-5 rounded-xl border border-red-400/30 px-4 py-2 text-sm text-red-200">Leave Family</button>}</section>
  </div>;
}