'use client';

import { useEffect, useMemo, useState } from 'react';
import { apiFetch } from '@/lib/api-client';
import { toast } from 'sonner';
import { AtSign, Check, ExternalLink, Loader2, Plus, ShieldCheck, Sparkles, Star, Users, X } from 'lucide-react';

const PLATFORMS = ['instagram','youtube','x','tiktok','facebook','linkedin','reddit','github','rss','website'];
const LABEL = { instagram:'Instagram', youtube:'YouTube', x:'X', tiktok:'TikTok', facebook:'Facebook', linkedin:'LinkedIn', reddit:'Reddit', github:'GitHub', rss:'RSS', website:'Website' };

export default function CirclesPage() {
  const [circles, setCircles] = useState([]); const [activeId, setActiveId] = useState('all'); const [detail, setDetail] = useState(null); const [sources, setSources] = useState([]); const [updates, setUpdates] = useState([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false);
  const [showAdd, setShowAdd] = useState(false); const [showCircle, setShowCircle] = useState(false); const [profile, setProfile] = useState(''); const [platform, setPlatform] = useState('instagram'); const [displayName, setDisplayName] = useState(''); const [suggestion, setSuggestion] = useState(null); const [targetCircle, setTargetCircle] = useState(''); const [circleName, setCircleName] = useState('');

  async function loadCircles() { const result = await apiFetch('/circles'); setCircles(result.circles || []); return result.circles || []; }
  async function loadSelection(id = activeId) {
    setLoading(true); try { const req = [apiFetch(id === 'all' ? '/circles/feed?limit=30' : `/circles/feed?circleId=${id}&limit=30`)]; if (id !== 'all') req.push(apiFetch(`/circles/${id}`)); const [feed, selected] = await Promise.all(req); setUpdates(feed.updates || []); setDetail(selected?.circle || null); setSources(selected?.sources || []); } catch (e) { toast.error(e.message); } finally { setLoading(false); }
  }
  useEffect(() => { loadCircles().then(() => loadSelection('all')).catch(e => { toast.error(e.message); setLoading(false); }); }, []);
  useEffect(() => { if (activeId !== 'all' || circles.length) loadSelection(activeId); }, [activeId]);

  const totalSources = useMemo(() => circles.reduce((sum,c) => sum + Number(c.sourceCount || 0), 0), [circles]);
  const worthSeeing = useMemo(() => circles.reduce((sum,c) => sum + Number(c.worthSeeing || 0), 0), [circles]);

  async function analyze() {
    if (!profile.trim()) return; setBusy(true);
    try { const result = await apiFetch('/circles/suggest', { method:'POST', body:JSON.stringify({ input:profile, platform, displayName }) }); setSuggestion(result.suggestion); setTargetCircle(result.suggestion?.circleId || (activeId !== 'all' ? activeId : '')); }
    catch(e){ toast.error(e.message); } finally { setBusy(false); }
  }
  async function addProfile() {
    if (!targetCircle || !profile.trim()) return; setBusy(true);
    try { const result = await apiFetch(`/circles/${targetCircle}/sources`, { method:'POST', body:JSON.stringify({ input:profile, platform, displayName }) }); const circle = circles.find(c => c.id === targetCircle); toast.success(`${result.source.displayName} added to ${circle?.name || 'Circle'}.`); setShowAdd(false); setProfile(''); setDisplayName(''); setSuggestion(null); setTargetCircle(''); await loadCircles(); if (activeId === targetCircle) await loadSelection(activeId); }
    catch(e){ toast.error(e.message); } finally { setBusy(false); }
  }
  async function createCircle(e) { e.preventDefault(); if(!circleName.trim()) return; setBusy(true); try { const result=await apiFetch('/circles',{method:'POST',body:JSON.stringify({name:circleName})}); setCircleName(''); setShowCircle(false); await loadCircles(); setActiveId(result.circle.id); toast.success('Circle created.'); } catch(e){toast.error(e.message);} finally{setBusy(false);} }

  return <div className="mx-auto max-w-6xl space-y-7 pb-32">
    <header className="rounded-[2rem] border border-white/10 bg-gradient-to-br from-pink-500/15 via-purple-500/10 to-cyan-500/10 p-6 md:p-8"><div className="flex flex-wrap items-start justify-between gap-5"><div><div className="mb-3 inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-3 py-1.5 text-xs font-black text-pink-100"><Sparkles className="h-3.5 w-3.5"/> SOCIAL, WITHOUT THE NOISE</div><h1 className="text-4xl font-black">Circles</h1><p className="mt-3 max-w-2xl leading-7 text-white/60">Keep the people, creators and topics you care about organized in one place. SnapNext only shows updates it can retrieve through real approved connections—never invented activity.</p></div><div className="flex gap-2"><button onClick={()=>setShowAdd(true)} className="inline-flex min-h-12 items-center gap-2 rounded-full bg-white px-5 text-sm font-black text-black"><AtSign className="h-4 w-4"/> Add @profile</button><button onClick={()=>setShowCircle(true)} aria-label="New Circle" className="grid h-12 w-12 place-items-center rounded-full border border-white/10 bg-white/5"><Plus className="h-5 w-5"/></button></div></div></header>

    <section className="grid gap-3 sm:grid-cols-3"><Stat label="Profiles organized" value={totalSources}/><Stat label="Your Circles" value={circles.length}/><Stat label="Worth seeing" value={worthSeeing} note="Real connected updates only"/></section>

    <section><div className="mb-4"><h2 className="text-2xl font-black">Your Circles</h2><p className="mt-1 text-sm text-white/45">Starter Circles help you begin; create any category that fits your life.</p></div><div className="grid grid-cols-2 gap-3 md:grid-cols-3 lg:grid-cols-6">{circles.map(c=><button key={c.id} onClick={()=>setActiveId(activeId===c.id?'all':c.id)} className={`min-h-36 rounded-3xl border p-4 text-left ${activeId===c.id?'border-pink-300/50 bg-pink-500/15':'border-white/10 bg-white/[0.035]'}`}><Users className="h-5 w-5 text-pink-200"/><h3 className="mt-5 font-black">{c.name}</h3><p className="mt-1 text-sm text-white/45">{c.sourceCount||0} profiles</p><p className={`mt-2 text-xs font-bold ${c.worthSeeing?'text-emerald-200':'text-white/30'}`}>{c.worthSeeing?`${c.worthSeeing} worth seeing`:'Caught up'}</p></button>)}</div></section>

    {activeId!=='all' && detail && <section className="rounded-[2rem] border border-white/10 bg-white/[0.03] p-5"><div className="flex items-start justify-between gap-4"><div><h2 className="text-2xl font-black">{detail.name}</h2><p className="mt-1 text-sm text-white/45">{detail.description||'Profiles that matter to you.'}</p></div><button onClick={()=>{setTargetCircle(activeId);setShowAdd(true);}} className="rounded-full bg-white px-4 py-2 text-sm font-black text-black">Add profile</button></div><div className="mt-5 grid gap-3 md:grid-cols-2">{sources.length?sources.map(s=><div key={s.id} className="flex items-center gap-3 rounded-2xl border border-white/10 bg-black/15 p-4"><div className="grid h-11 w-11 place-items-center rounded-xl bg-white/10 text-xs font-black uppercase">{s.platform.slice(0,2)}</div><div className="min-w-0 flex-1"><p className="truncate font-black">{s.displayName}</p><p className="truncate text-xs text-white/45">@{String(s.handle||'').replace(/^@/,'')} · {LABEL[s.platform]||s.platform}</p><Connection source={s}/></div>{s.priority>=80&&<Star className="h-4 w-4 fill-current text-amber-200"/>}{s.profileUrl&&<a href={s.profileUrl} target="_blank" rel="noreferrer" className="grid h-9 w-9 place-items-center rounded-full bg-white/5"><ExternalLink className="h-4 w-4"/></a>}</div>):<Empty text="No profiles yet. Add @NBA, @NASA, a friend, creator or any profile you care about."/>}</div></section>}

    <section className="rounded-[2rem] border border-white/10 bg-white/[0.03] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-black">{activeId==='all'?'Catch up':'Worth seeing'}</h2><p className="mt-1 text-sm text-white/45">A finite feed from sources SnapNext is genuinely allowed to read.</p></div><span className="rounded-full border border-emerald-300/15 bg-emerald-300/10 px-3 py-1 text-xs font-bold text-emerald-100">No fake updates</span></div><div className="mt-5 space-y-3">{loading?<div className="grid min-h-32 place-items-center"><Loader2 className="h-5 w-5 animate-spin"/></div>:updates.length?updates.map(u=><article key={u.id} className="rounded-2xl border border-white/10 bg-black/15 p-4"><div className="flex justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-pink-200">{LABEL[u.platform]||u.platform}</p><h3 className="mt-1 font-black">{u.title||u.source?.displayName||'Update'}</h3>{u.excerpt&&<p className="mt-2 text-sm leading-6 text-white/55">{u.excerpt}</p>}</div><span className="text-xs font-bold text-white/35">{u.importanceScore||0}/100</span></div>{u.externalUrl&&<a href={u.externalUrl} target="_blank" rel="noreferrer" className="mt-3 inline-flex items-center gap-1 text-xs font-bold text-pink-200">Open original <ExternalLink className="h-3 w-3"/></a>}</article>):<Empty text={totalSources?'You’re caught up. Live updates appear only when an approved connector has real access.':'Add profiles to build your social world without rebuilding another endless feed.'}/>}</div></section>

    <section className="rounded-[2rem] border border-cyan-300/15 bg-cyan-400/[0.05] p-5"><div className="flex gap-3"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-cyan-200"/><p className="text-sm leading-6 text-white/55"><b className="text-white">You stay in control.</b> Platform authorization will be added progressively using official APIs/OAuth. Unsupported profiles remain useful shortcuts and always show zero updates rather than pretending they are synchronized.</p></div></section>

    {showAdd&&<Modal title="Add @profile" close={()=>{setShowAdd(false);setSuggestion(null);}}><input autoFocus value={profile} onChange={e=>{setProfile(e.target.value);setSuggestion(null);}} placeholder="@NBA or paste profile URL" className="min-h-12 w-full rounded-2xl border border-white/10 bg-white/5 px-4 outline-none"/><div className="mt-3 flex gap-2 overflow-x-auto pb-1">{PLATFORMS.map(p=><button key={p} onClick={()=>setPlatform(p)} className={`shrink-0 rounded-full px-3 py-2 text-xs font-bold ${platform===p?'bg-white text-black':'bg-white/5 text-white/55'}`}>{LABEL[p]}</button>)}</div><input value={displayName} onChange={e=>setDisplayName(e.target.value)} placeholder="Display name (optional)" className="mt-3 min-h-11 w-full rounded-2xl border border-white/10 bg-white/5 px-4 text-sm outline-none"/>{!suggestion?<button onClick={analyze} disabled={busy||!profile.trim()} className="mt-4 flex min-h-12 w-full items-center justify-center gap-2 rounded-2xl bg-gradient-to-r from-pink-500 to-purple-600 font-black disabled:opacity-40">{busy?<Loader2 className="h-4 w-4 animate-spin"/>:<Sparkles className="h-4 w-4"/>} Suggest Circle</button>:<><div className="mt-4 rounded-2xl border border-pink-300/15 bg-pink-500/10 p-4"><p className="text-xs font-black uppercase tracking-wider text-pink-200">SnapNext suggestion</p><p className="mt-2 font-black">{suggestion.suggestedCircle||'You decide'}</p><p className="mt-1 text-sm text-white/50">{suggestion.reason}</p></div><p className="mb-2 mt-4 text-sm font-bold">Add to</p><div className="grid grid-cols-2 gap-2">{circles.map(c=><button key={c.id} onClick={()=>setTargetCircle(c.id)} className={`flex items-center justify-between rounded-2xl border px-3 py-3 text-left text-sm font-bold ${targetCircle===c.id?'border-pink-300/50 bg-pink-500/15':'border-white/10 bg-white/[0.03]'}`}>{c.name}{targetCircle===c.id&&<Check className="h-4 w-4"/>}</button>)}</div><button onClick={addProfile} disabled={busy||!targetCircle} className="mt-4 min-h-12 w-full rounded-2xl bg-white font-black text-black disabled:opacity-40">Add profile</button></>}</Modal>}
    {showCircle&&<Modal title="New Circle" close={()=>setShowCircle(false)}><form onSubmit={createCircle}><p className="mb-4 text-sm text-white/45">Create any category that fits your life: AI, Cars, Recipes, Fitness, Travel or anything else.</p><input autoFocus value={circleName} onChange={e=>setCircleName(e.target.value)} placeholder="Circle name" className="min-h-12 w-full rounded-2xl border border-white/10 bg-white/5 px-4 outline-none"/><button disabled={busy||!circleName.trim()} className="mt-4 min-h-12 w-full rounded-2xl bg-white font-black text-black disabled:opacity-40">Create Circle</button></form></Modal>}
  </div>;
}

function Stat({label,value,note}){return <div className="rounded-3xl border border-white/10 bg-white/[0.035] p-5"><p className="text-sm text-white/45">{label}</p><p className="mt-2 text-3xl font-black">{value}</p>{note&&<p className="mt-1 text-xs text-white/30">{note}</p>}</div>}
function Empty({text}){return <div className="col-span-full rounded-2xl border border-dashed border-white/10 p-6 text-center text-sm text-white/45">{text}</div>}
function Connection({source}){const text=source.connectionStatus==='active'?'Connected':source.connectionMode==='link_only'?'Saved profile · link only':'Authorization/setup required';return <p className="mt-1 text-[11px] text-white/35">{text}</p>}
function Modal({title,close,children}){return <div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-black/80 p-4 backdrop-blur-xl"><div className="w-full max-w-lg rounded-[2rem] border border-white/10 bg-[#12091b] p-6"><div className="mb-5 flex items-center justify-between"><h2 className="text-2xl font-black">{title}</h2><button onClick={close} className="grid h-10 w-10 place-items-center rounded-full bg-white/5"><X className="h-4 w-4"/></button></div>{children}</div></div>}
